### ISSUE TITLE
What does cut path mean in relational symbolic execution?

### ISSUE THREAD

**Issue by Luweicai** [binsec/binsec#25]
I complie a example with a compiler compcert and verified it with `checkct`.
The result is that it is secure but is much more faster than the gcc compiled version.
I find that it might becasue the `cut` path show in the result.
What does cut path mean?
```
[sse:warning] Cut path 3 (non executable) @ 0x00000000
[sse:warning] Cut path 2 (non executable) @ 0xffffffffffffffff
[sse:warning] Cut path 1 (non executable) @ 0xfffffffffffffffe
[sse:info] Empty path worklist: halting ...
[sse:info] SMT queries
             Preprocessing simplifications
               total          68
               sat            31
               unsat          36
               constant enum  1

             Satisfiability queries
               total          2
               sat            2
               unsat          0
               unknown        0
               time           0.00
               average        0.00

           Exploration
             total paths                      3
             completed/cut paths              0
             pending paths                    0
             stale paths                      3
             failed assertions                0
             branching points                 33
             max path depth                   737
             visited instructions (unrolled)  737
             visited instructions (static)    520


[checkct:result] Program status is : secure (0.132)
[checkct:info] 0 visited path covering 520 instructions
[checkct:info] 33 / 33 control flow checks pass
[checkct:info] 283 / 283 memory access checks pass
```

**Comment by recoules** [comment]
Hi @Luweicai,

The fact that `checkct` gives a `secure` status is here actually a bug. Here, it should answer `unknown` since some paths were not explored (`stale paths` which correspond to the 3 cuts). It will be fixed in the next release.
This is more likely due to the fact the compiler used some indirect function pointers that were not initialized.
This is in line with the question in #24, I think you should try to put some more command in your script, especially importing all the sections you think may be important (e.g. `load sections .text, .rodata, .data, .got.plt, .plt from file`).

**Comment by Luweicai** [comment]
Hi, @recoules . Quite thank you for your reply. I have another problem that is there any doc about how to write the correct sse script ( as need to add the information load sections .text, .rodata, .data, .got.plt, .plt I need to write). I find that the checkct.cfg in toturial is not enough for me to write the exactlly right configure file.

**Comment by recoules** [comment]
We have to write other tutorials. Adding a more advanced example of `checkct` is indeed a good target.

For now, you can have a look to others SSE tutorials since `checkct` is a monitor for it, any configuration for SSE works/may be relevant. You will also find the language reference used by the script: https://github.com/binsec/binsec/blob/master/doc/sse/references.md

**Comment by Luweicai** [comment]
Quite thank you.
