### ISSUE TITLE
Weird behaviour when returning from function on arm

### ISSUE THREAD

**Issue by cchr-ledger** [binsec/binsec#34]
Hello,

I am using the checkct plugin to analyse an arm binary, that contains the following snippets:
```console
[...]
   317b0: 0d f5 13 7d   add.w   sp, sp, #588
   317b4: bd e8 00 0f   pop.w   {r8, r9, r10, r11}
   317b8: f0 bd         pop     {r4, r5, r6, r7, pc}
[...]
   369da: 41 77         strb    r1, [r0, #29]
   369dc: 03 b0         add     sp, #12
   369de: bd e8 00 0f   pop.w   {r8, r9, r10, r11}
   369e2: f0 bd         pop     {r4, r5, r6, r7, pc}
[...]
```
Now when using the following script:
```console
load sections .text from file
starting from <fn_to_analyze>
with concrete stack pointer
lr := 0x8badf00d ^ 1
reach 0x369e2 then print @[sp + 16,4]
reach * 0x317b0
reach * 0x317b1
reach * 0x317b4
halt at 0x8badf00d ^ 1
explore all
```
the analysis returns
```console
[sse:info] Load section .text (0x00030b00, 0x4225a)
[sse:result] Path 238 reached address 0x000369e2 (0 to go)
[sse:result] Value @[(sp<32> + 16<32>),4] : 0x000317b1
```
and then keeps running without printing anything else, until it gets killed by the kernel. 
So it seems that address `0x317b0/1` is never reached, which is weird.

What's more if I interrupt the process before it gets killed, the output is always exactly the same (apart from the time, that is):
```console
^C[sse:info] SMT queries
             Preprocessing simplifications
               total          747958
               sat            550
               unsat          743046
               constant enum  4362
             
             Satisfiability queries
               total          506
               sat            237
               unsat          269
               unknown        0
               time           25.51
               average        0.05
             
           Exploration
             total paths                      238
             completed/cut paths              0
             pending paths                    238
             stale paths                      0
             failed assertions                0
             branching points                 5699
             max path depth                   1489483
             visited instructions (unrolled)  1489483
             visited instructions (static)    3526
             
           
[checkct:result] Program status is : unknown (30.945)
[checkct:info] 0 visited path covering 3526 instructions
[checkct:info] 5699 / 5699 control flow checks pass
[checkct:info] 737702 / 737702 memory access checks pass
[checkct:warning] Exploration is incomplete:
                  - timeout has left (at least) 238 pending paths (-sse-timeout)
```
Do you have an idea as to what could be happening?

**Comment by recoules** [comment]
Hi @cchr-ledger,

At first glance, it looks like the SMT solver runs into an `OutOfMemory` error. 

Once it starts "freezing", does the solver time (in `Satisfiability queries`) increase the same way the global time ? If yes, I think it is an OOM due to a very hard formula to solve (it may be due to writes with symbolic addresses close to the stack location of the return address).
*Note*: if you have `curses` installed (`opam install curses`), you should be able to switch between log and monitor mode (https://github.com/binsec/binsec/blob/master/doc/sse/exploration_board.md) and follow different statistics on the fly.

You may also try with another solver if you have one installed (e.g. `-smt-solver z3`). It may die all the same, but as it will be an independent process, `binsec` will get an `unknown` result instead of being killed by the OS.

Regards,
Frédéric

**Comment by cchr-ledger** [comment]
Thanks a lot for the help, I was able to make it work by making more things concrete.
